import {library} from '@fortawesome/fontawesome-svg-core'
import {
    faAngleDoubleLeft,
    faAngleLeft,
    faAngleRight,
    faCheck,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCog,
    faEllipsisV,
    faExclamationTriangle,
    faExpandAlt,
    faGripHorizontal,
    faHome,
    faKeyboard,
    faMouse,
    faPlus,
    faQuestion,
    faSave,
    faSearch,
    faSearchMinus,
    faSearchPlus,
    faThumbtack,
    faTimes,
} from '@fortawesome/free-solid-svg-icons'

import {faEdit, faQuestionCircle, faTrashAlt, faUser,} from '@fortawesome/free-regular-svg-icons'

library.add(
  faEdit,
  faTrashAlt,
  faCheck,
  faTimes,
  faHome,
  faSave,
  faKeyboard,
  faMouse,
  faCog,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faExclamationTriangle,
  faQuestionCircle,
  faSearchPlus,
  faSearchMinus,
  faUser,
  faThumbtack,
  faSearch,
  faGripHorizontal,
  faExpandAlt,
  faPlus,
  faQuestion,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleLeft,
  faEllipsisV,
)
